spring.application.name=system

# MySQL Connection
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/hotel_reservation
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Show SQL in console (helpful for debugging)
logging.level.org.springframework.jdbc=DEBUG

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
upload.path=uploads/payments/
